# Assignment 8

## A

In [253]:
import numpy as np
import random as rand

In [268]:
t = 1024
M = np.array([[.3,   0.6,  0,    0,    0,    0,    0,   0,   0,   0],
             [.7,   0.2,  0,    0,    0,    0,    0,   0.1, 0,   0],
             [0,    0.2,  0,    0.3,  0.3,  0,    0,   0,   0,   0],
             [0,    0,    0.5,  0,    0.2,  0.3,  0,   0,   0,   0],
             [0,    0,   0.5,  0.3,  0,    0.7,  0,   0,   0,   0],
             [0,    0,    0,    0.4,  0.4,  0,    0,   0,   0,   0],
             [0,    0,    0,    0,    0.1,  0,    0,   0.7, 0.5, 0],
             [0,    0,    0,    0,    0,    0,    0.6, 0,   0,   0.5],
             [0,    0,    0,    0,    0,    0,    0.4, 0,   0,   0.5],
             [0,    0,    0,    0,    0,    0,    0,   0.2, 0.5, 0]])
P = M.copy()
q0 = np.zeros((M.shape[0], 1))
q0[0] = 1

In [269]:
def mat_pow(P, t, recursive=False):
    if recursive:
        if t == 0:
            return P
        else:
            Pi = mat_pow(P, t//2, recursive=recursive)
            print(np.all(Pi >= 0))
            return Pi @ Pi
        
    else:
        Pi = P
        for i in range(t):
            print(np.all(Pi >= 0))
            Pi = Pi @ P
            
        return Pi

**Recursive Matrix Power**

In [270]:
mat_pow(P, t, recursive=True) @ q0

True
True
True
True
True
True
True
True
True
True
True


array([[ 0.05739691],
       [ 0.06696306],
       [ 0.08219028],
       [ 0.09539943],
       [ 0.13392613],
       [ 0.09173022],
       [ 0.15827633],
       [ 0.13392613],
       [ 0.10227086],
       [ 0.07792065]])

**Matrix Power**

In [271]:
mat_pow(P, t, recursive=False) @ q0

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


array([[ 0.05739691],
       [ 0.06696306],
       [ 0.08219028],
       [ 0.09539943],
       [ 0.13392613],
       [ 0.09173022],
       [ 0.15827633],
       [ 0.13392613],
       [ 0.10227086],
       [ 0.07792065]])

In [258]:
def state_prop(P, t, q0):
    q_star = q0
    for i in range(t):
        q_star = P @ q_star
        
    return q_star

In [259]:
state_prop(P, t, q0)

array([[ 0.05739691],
       [ 0.06696306],
       [ 0.08219028],
       [ 0.09539943],
       [ 0.13392613],
       [ 0.09173022],
       [ 0.15827633],
       [ 0.13392613],
       [ 0.10227086],
       [ 0.07792065]])

In [210]:
def rand_walk(P, t, t0, q0):
    # burn in
    q_star = q0.astype(int)
    for i in range(t0):
        W = np.sum(P[:,np.flatnonzero(q_star)])
        w = np.cumsum(P[:,np.flatnonzero(q_star)]/W)
        p = rand.uniform(0,1)
        k = np.argmax(w>p)
        
        q_star = np.zeros(q_star.shape, dtype=int)
        q_star[k] = 1
        
    # walk
    counts = np.zeros(q_star.shape)
    for j in range(t):
        W = np.sum(P[:,np.flatnonzero(q_star)])
        w = np.cumsum(P[:,np.flatnonzero(q_star)]/W)
        p = rand.uniform(0,1)
        k = np.argmax(w>p)
        counts[k] += 1
        
        q_star = np.zeros(q_star.shape, dtype=int)
        q_star[k] = 1
        
        
    return counts/np.linalg.norm(counts, ord=1)
        

In [214]:
t0 = 100
rand_walk(P, t, t0, q0)

array([[ 0.06152344],
       [ 0.07128906],
       [ 0.06445312],
       [ 0.08300781],
       [ 0.11816406],
       [ 0.08691406],
       [ 0.17480469],
       [ 0.1484375 ],
       [ 0.10839844],
       [ 0.08300781]])

In [236]:
w, v = np.linalg.eig(M)
qq = (v[:,0]/sum(v[:,0])).reshape((10,1)).astype(float)
qq

C:\Users\Lukas Gust\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  


array([[ 0.05739691],
       [ 0.06696306],
       [ 0.08219028],
       [ 0.09539943],
       [ 0.13392613],
       [ 0.09173022],
       [ 0.15827633],
       [ 0.13392613],
       [ 0.10227086],
       [ 0.07792065]])

## B

In [242]:
q0 = np.full((10,1), 0.1)

for t in range(0,11):
    print(2**t)
    print(abs((mat_pow(P, 2**t, recursive=True) @ q0) - qq))

1
[[ 0.02960309]
 [ 0.02703694]
 [ 0.01280972]
 [ 0.00139943]
 [ 0.00792613]
 [ 0.00826978]
 [ 0.02127633]
 [ 0.02092613]
 [ 0.01527086]
 [ 0.01092065]]
2
[[ 0.02195309]
 [ 0.02055694]
 [ 0.01052972]
 [ 0.00254057]
 [ 0.00088387]
 [ 0.00762978]
 [ 0.01856633]
 [ 0.01975613]
 [ 0.01514086]
 [ 0.01063065]]
4
[[ 0.01166756]
 [ 0.01074862]
 [ 0.00838244]
 [ 0.00681501]
 [ 0.00870635]
 [ 0.00784605]
 [ 0.01502999]
 [ 0.01715087]
 [ 0.01324261]
 [ 0.00874256]]
8
[[ 0.0017451 ]
 [ 0.001222  ]
 [ 0.00602543]
 [ 0.00759919]
 [ 0.01074098]
 [ 0.00760897]
 [ 0.00909373]
 [ 0.01144387]
 [ 0.00888192]
 [ 0.00552214]]
16
[[ 0.00173962]
 [ 0.00184341]
 [ 0.00238576]
 [ 0.00361466]
 [ 0.00524966]
 [ 0.00373381]
 [ 0.00241648]
 [ 0.00414493]
 [ 0.00322939]
 [ 0.00161007]]
32
[[  3.27589102e-04]
 [  2.85436730e-04]
 [  1.61961243e-04]
 [  3.07069333e-04]
 [  4.53667470e-04]
 [  3.19514335e-04]
 [  1.85719803e-04]
 [  5.00011077e-04]
 [  3.88479020e-04]
 [  7.35837447e-05]]
64
[[  2.74619987e-06]
 [  5.5

In [260]:
q0 = np.full((10,1), 0.1)

for t in range(0,11):
    print(2**t)
    print(abs((state_prop(P, 2**t, q0)) - qq))

1
[[ 0.03260309]
 [ 0.03303694]
 [ 0.00219028]
 [ 0.00460057]
 [ 0.01607387]
 [ 0.01173022]
 [ 0.02827633]
 [ 0.02392613]
 [ 0.01227086]
 [ 0.00792065]]
2
[[ 0.02960309]
 [ 0.02703694]
 [ 0.01280972]
 [ 0.00139943]
 [ 0.00792613]
 [ 0.00826978]
 [ 0.02127633]
 [ 0.02092613]
 [ 0.01527086]
 [ 0.01092065]]
4
[[ 0.02195309]
 [ 0.02055694]
 [ 0.01052972]
 [ 0.00254057]
 [ 0.00088387]
 [ 0.00762978]
 [ 0.01856633]
 [ 0.01975613]
 [ 0.01514086]
 [ 0.01063065]]
8
[[ 0.01166756]
 [ 0.01074862]
 [ 0.00838244]
 [ 0.00681501]
 [ 0.00870635]
 [ 0.00784605]
 [ 0.01502999]
 [ 0.01715087]
 [ 0.01324261]
 [ 0.00874256]]
16
[[ 0.0017451 ]
 [ 0.001222  ]
 [ 0.00602543]
 [ 0.00759919]
 [ 0.01074098]
 [ 0.00760897]
 [ 0.00909373]
 [ 0.01144387]
 [ 0.00888192]
 [ 0.00552214]]
32
[[ 0.00173962]
 [ 0.00184341]
 [ 0.00238576]
 [ 0.00361466]
 [ 0.00524966]
 [ 0.00373381]
 [ 0.00241648]
 [ 0.00414493]
 [ 0.00322939]
 [ 0.00161007]]
64
[[  3.27589102e-04]
 [  2.85436730e-04]
 [  1.61961243e-04]
 [  3.07069333e-0

## C

Pros and Cons

## D

In [262]:
(M @ qq) - qq

array([[  4.85722573e-17],
       [  3.60822483e-16],
       [ -5.55111512e-17],
       [  1.11022302e-16],
       [  1.38777878e-16],
       [ -6.93889390e-17],
       [ -4.44089210e-16],
       [  8.32667268e-17],
       [ -1.11022302e-16],
       [ -1.24900090e-16]])

In [272]:
M

array([[ 0.3,  0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.7,  0.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0.1,  0. ,  0. ],
       [ 0. ,  0.2,  0. ,  0.3,  0.3,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.5,  0. ,  0.2,  0.3,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.5,  0.3,  0. ,  0.7,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.4,  0.4,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.1,  0. ,  0. ,  0.7,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.6,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.4,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.2,  0.5,  0. ]])

Node 3 w/ p=.3, Node 5 w/ p=.3, Node 6 w/ p=.4