# A06 Regression

In [1]:
import numpy as np

In [2]:
def read(fname):
    vals = []
    with open(fname, 'rb') as fd:
        for line in fd:
            if not line.strip():
                continue
            s = list(map(float, line.strip().split()))
            vals.append(s)
            
    return np.array(vals)

In [3]:
X = read('./X.dat')
print(X.shape)

Y = read('./Y.dat')
print(Y.shape)

(100, 15)
(100, 1)


## Q1 A

In [4]:
A, r , _, __ = np.linalg.lstsq(X, Y)

In [5]:
print('Coefficients: \n' + str(A))

Coefficients: 
[[  6.41766065]
 [  0.26256845]
 [  4.88999221]
 [  1.2352192 ]
 [  1.70850062]
 [  5.53776502]
 [  8.48696144]
 [ -1.46156254]
 [ 10.69158285]
 [  5.86161369]
 [  5.75864638]
 [  5.32731348]
 [  4.71614203]
 [  8.82500343]
 [  7.46678008]]


In [6]:
print('Squared Residual: ' + str(r[0]))
print('Residual: ' + str(r[0]**.5))

Squared Residual: 366817.621755
Residual: 605.654705055


In [7]:
def ridge_regress(x, y, s):
    A = np.linalg.inv(x.T.dot(x) + (s**2)*np.eye(15)).dot(x.T).dot(y)/s
    A *= s
    r = np.linalg.norm(y - x.dot(A))
    return A, r

In [8]:
ss = [1,5,10,15,20,25,30]

for s in ss:
    A, r = ridge_regress(X, Y, s)
    
    print('s: ' + str(s))
    print('Coeffs: \n' + str(A))
    print('Residual: ' + str(r))
    print()

s: 1
Coeffs: 
[[  6.41329395]
 [  0.2708133 ]
 [  4.89271436]
 [  1.2370286 ]
 [  1.71154643]
 [  5.53618856]
 [  8.48291189]
 [ -1.45037748]
 [ 10.68433057]
 [  5.86355149]
 [  5.75774639]
 [  5.32605177]
 [  4.71665642]
 [  8.81745469]
 [  7.46193719]]
Residual: 605.654905335

s: 5
Coeffs: 
[[  6.3144084 ]
 [  0.45926442]
 [  4.95292738]
 [  1.28104106]
 [  1.78287946]
 [  5.50081295]
 [  8.38877667]
 [ -1.19348765]
 [ 10.51632748]
 [  5.90546875]
 [  5.7370862 ]
 [  5.29779357]
 [  4.72762651]
 [  8.6447522 ]
 [  7.35073904]]
Residual: 605.770819125

s: 10
Coeffs: 
[[  6.06445027]
 [  0.95121332]
 [  5.09134618]
 [  1.42164898]
 [  1.98614387]
 [  5.41379184]
 [  8.12756065]
 [ -0.51097348]
 [ 10.05592736]
 [  5.9917465 ]
 [  5.6814612 ]
 [  5.22879208]
 [  4.74892976]
 [  8.19207991]
 [  7.05585616]]
Residual: 607.156835367

s: 15
Coeffs: 
[[ 5.7770121 ]
 [ 1.54606466]
 [ 5.21987723]
 [ 1.64877225]
 [ 2.2710863 ]
 [ 5.31594819]
 [ 7.77619758]
 [ 0.34013566]
 [ 9.44990537]
 [ 6.0437

## Q1 B

In [9]:
X1 = X[0:66]
X1_C = X[66:]

Y1 = Y[0:66]
Y1_C = Y[66:]

X2 = X[34:100]
X2_C = X[0:34]

Y2 = Y[34:100]
Y2_C = Y[0:34]

X3 = np.vstack([X[0:33], X[67:100]])
X3_C = X[33:67]

Y3 = np.vstack([Y[0:33], Y[67:100]])
Y3_C = Y[33:67]

In [10]:
A1, r1, _, _ = np.linalg.lstsq(X1, Y1)
print('Coeffs: \n' + str(A1))
print('Residual: ' + str(r1[0]**.5))
cr1 = np.linalg.norm(Y1_C - X1_C.dot(A1))
print('Cross-Val Residual: ' + str(cr1))

Coeffs: 
[[ 2.93837499]
 [ 5.30919625]
 [ 5.41512021]
 [-3.55623211]
 [ 1.32133517]
 [ 5.79768578]
 [ 9.37297505]
 [-2.46096478]
 [ 8.58540281]
 [ 7.37732721]
 [ 6.63872593]
 [ 7.6307665 ]
 [ 6.36390943]
 [ 7.36108316]
 [ 6.28496322]]
Residual: 441.121873562
Cross-Val Residual: 483.02361036


In [11]:
A2, r2, _, _ = np.linalg.lstsq(X2, Y2)
print('Coeffs: \n' + str(A2))
print('Residual: ' + str(r2[0]**.5))
cr2 = np.linalg.norm(Y2_C - X2_C.dot(A2))
print('Cross-Val Residual: ' + str(cr2)) 

Coeffs: 
[[  7.35734429]
 [ -2.05293525]
 [  5.82743635]
 [  2.22701997]
 [  2.80308908]
 [  6.00253633]
 [ 11.17105387]
 [ -2.62408297]
 [ 12.47457376]
 [  3.13478809]
 [  3.90879956]
 [  3.2143665 ]
 [  5.17503073]
 [ 10.47767815]
 [  6.90077289]]
Residual: 460.317108454
Cross-Val Residual: 432.369392276


In [12]:
A3, r3, _, _ = np.linalg.lstsq(X3, Y3)
print('Coeffs: \n' + str(A3))
print('Residual: ' + str(r3[0]**.5))
cr3 = np.linalg.norm(Y3_C - X3_C.dot(A3))
print('Cross-Val Residual: ' + str(cr3)) 

Coeffs: 
[[  6.46688093]
 [ -0.4190106 ]
 [  5.05411275]
 [  3.72605859]
 [  1.41241571]
 [  6.6715221 ]
 [  4.55263264]
 [ -1.29318511]
 [ 11.37494853]
 [  7.69240024]
 [  4.88347493]
 [  5.5831921 ]
 [  2.72501327]
 [  8.77743236]
 [  8.80027736]]
Residual: 475.645392334
Cross-Val Residual: 411.176725128


In [13]:
cr_avg = (cr1+cr2+cr3)/3
cr_avg

442.18990925482331

### Ridge Regression 

In [20]:
crr1 = []
for s in ss:
    A1, r1 = ridge_regress(X1, Y1, s)
    print('s: ' + str(s))
    print('Coeffs: \n' + str(A1))
    print('Residual: ' + str(r1))
    cr1 = np.linalg.norm(Y1_C - X1_C.dot(A1))
    crr1.append(cr1)
    print('Cross-Val Residual: ' + str(cr1))
    print()

s: 1
Coeffs: 
[[ 2.94404236]
 [ 5.3054141 ]
 [ 5.41459831]
 [-3.53881916]
 [ 1.3237142 ]
 [ 5.79300275]
 [ 9.36109156]
 [-2.4414278 ]
 [ 8.58310647]
 [ 7.37552955]
 [ 6.63687018]
 [ 7.62214993]
 [ 6.35541118]
 [ 7.36016142]
 [ 6.28281207]]
Residual: 441.122367778
Cross-Val Residual: 482.731584281

s: 5
Coeffs: 
[[ 3.07046758]
 [ 5.22679266]
 [ 5.40182967]
 [-3.14687926]
 [ 1.38749895]
 [ 5.6950534 ]
 [ 9.09843625]
 [-2.00692676]
 [ 8.51753155]
 [ 7.32770509]
 [ 6.59289145]
 [ 7.4352481 ]
 [ 6.16549435]
 [ 7.33280277]
 [ 6.23079288]]
Residual: 441.398148722
Cross-Val Residual: 476.42195304

s: 10
Coeffs: 
[[ 3.36983384]
 [ 5.07320362]
 [ 5.36146303]
 [-2.16741663]
 [ 1.6234979 ]
 [ 5.49911213]
 [ 8.4756159 ]
 [-0.95856063]
 [ 8.25577877]
 [ 7.15555267]
 [ 6.46167969]
 [ 7.01837492]
 [ 5.71189711]
 [ 7.21181187]
 [ 6.07551326]]
Residual: 444.403738592
Cross-Val Residual: 462.924744963

s: 15
Coeffs: 
[[ 3.66982193]
 [ 4.94325791]
 [ 5.30138266]
 [-1.04077209]
 [ 2.00512126]
 [ 5.32657187

In [15]:
crr2 = []
for s in ss:
    A2, r2 = ridge_regress(X2, Y2, s)
    print('s: ' + str(s))
    print('Coeffs: \n' + str(A2))
    print('Residual: ' + str(r2))
    cr2 = np.linalg.norm(Y2_C - X2_C.dot(A2))
    crr2.append(cr2)
    print('Cross-Val Residual: ' + str(cr2))
    print()

s: 1
Coeffs: 
[[  7.34917723]
 [ -2.03172203]
 [  5.83355116]
 [  2.22956854]
 [  2.79859205]
 [  6.0000272 ]
 [ 11.15481816]
 [ -2.59747264]
 [ 12.45891622]
 [  3.13997222]
 [  3.90951741]
 [  3.21317438]
 [  5.18287443]
 [ 10.45935566]
 [  6.89435529]]
Residual: 460.317884754
Cross-Val Residual: 432.12549152

s: 5
Coeffs: 
[[  7.16954541]
 [ -1.56520285]
 [  5.95878832]
 [  2.28753178]
 [  2.71672878]
 [  5.94207844]
 [ 10.7962827 ]
 [ -2.01450296]
 [ 12.10452679]
 [  3.25622609]
 [  3.93209171]
 [  3.19342451]
 [  5.34537399]
 [ 10.05442627]
 [  6.75117413]]
Residual: 460.737029154
Cross-Val Residual: 426.930452699

s: 10
Coeffs: 
[[  6.75422925]
 [ -0.48709288]
 [  6.17314603]
 [  2.44474621]
 [  2.65413605]
 [  5.78735867]
 [  9.94923011]
 [ -0.68280604]
 [ 11.20649535]
 [  3.5390986 ]
 [  4.03174105]
 [  3.20106966]
 [  5.63882215]
 [  9.10526219]
 [  6.40620748]]
Residual: 464.928665182
Cross-Val Residual: 416.072928284

s: 15
Coeffs: 
[[  6.32480315]
 [  0.61444606]
 [  6.26316

In [16]:
crr3 = []
for s in ss:
    A3, r3 = ridge_regress(X3, Y3, s)
    print('s: ' + str(s))
    print('Coeffs: \n' + str(A3))
    print('Residual: ' + str(r3))
    cr3 = np.linalg.norm(Y3_C - X3_C.dot(A3))
    crr3.append(cr3)
    print('Cross-Val Residual: ' + str(cr3))
    print()

s: 1
Coeffs: 
[[  6.45870259]
 [ -0.40370896]
 [  5.05268058]
 [  3.71693032]
 [  1.43151615]
 [  6.66021274]
 [  4.56317342]
 [ -1.27752969]
 [ 11.3552267 ]
 [  7.69731797]
 [  4.88503877]
 [  5.57929829]
 [  2.73294889]
 [  8.76322162]
 [  8.78680155]]
Residual: 475.645961536
Cross-Val Residual: 410.998376688

s: 5
Coeffs: 
[[  6.27868637]
 [ -0.06660617]
 [  5.02406276]
 [  3.53713162]
 [  1.82778246]
 [  6.42702911]
 [  4.77829747]
 [ -0.92188075]
 [ 10.92920984]
 [  7.78879439]
 [  4.91708242]
 [  5.49894605]
 [  2.89687172]
 [  8.45265813]
 [  8.49147131]]
Residual: 475.944598146
Cross-Val Residual: 407.57419476

s: 10
Coeffs: 
[[ 5.86637883]
 [ 0.72102376]
 [ 4.97519893]
 [ 3.26225789]
 [ 2.59429263]
 [ 5.9854219 ]
 [ 5.16685421]
 [-0.02101353]
 [ 9.98082325]
 [ 7.87560346]
 [ 4.97394388]
 [ 5.34183765]
 [ 3.21268114]
 [ 7.74422331]
 [ 7.81301552]]
Residual: 478.784353367
Cross-Val Residual: 402.915480514

s: 15
Coeffs: 
[[ 5.46264336]
 [ 1.5453729 ]
 [ 4.94256459]
 [ 3.1651814 

In [17]:
ridge_avg = np.vstack([crr1, crr2, crr3]).mean(axis=0)
print(ridge_avg.min())
print(ss[ridge_avg.argmin()])

417.45704279
20


The approach with the lowest average cross-validation residual is ridge regression with $s=20$.

## Q2

In [18]:
W = read('./W.dat')
print(W.shape)

M = read('./M.dat')
print(M.shape)

(80, 1)
(80, 100)


In [19]:
r = W
s = np.zeros(100)
for _ in range(1000):
    j = np.argmax(r.T.dot(M))
    s[j] = 1
    r = r - np.reshape(M[:,j], (80,1))
    
    print('Epoch: ' + str(_))
    print('Entry: ' + str(j))
    print(np.linalg.norm(r))
    print()
    if not np.count_nonzero(r):
        break
    
print(s)

Epoch: 0
Entry: 42
14.5258390463

Epoch: 1
Entry: 65
11.4455231423

Epoch: 2
Entry: 15
9.2736184955

Epoch: 3
Entry: 64
6.7082039325

Epoch: 4
Entry: 88
0.0

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
